import React from "react";
import { useNavigate } from "react-router-dom";
import { Sparkles, Award, ArrowRight, BrainCircuit, BarChart3, ListChecks } from "lucide-react";
import { ThemeToggle } from "../components/ThemeToggle";

export const Landing: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="relative min-h-screen bg-slate-50 text-slate-900 flex flex-col justify-between overflow-hidden transition-colors duration-200 dark:bg-slate-950 dark:text-slate-100">
      {/* Background glow elements */}
      <div className="absolute top-[-10%] left-[-10%] -z-10 h-[500px] w-[500px] rounded-full bg-indigo-500/10 blur-[100px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] -z-10 h-[500px] w-[500px] rounded-full bg-purple-500/10 blur-[100px] pointer-events-none" />

      {/* Header / Top Brand Nav */}
      <header className="w-full border-b border-slate-200 bg-white/70 backdrop-blur-md sticky top-0 z-50 transition-colors dark:border-slate-900 dark:bg-slate-950/50">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2 text-xl font-bold tracking-tight text-slate-900 dark:text-white">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-tr from-indigo-500 via-purple-500 to-pink-500 shadow-lg shadow-indigo-500/25">
              <Sparkles className="h-5 w-5 text-white" />
            </div>
            <span className="bg-gradient-to-r from-slate-900 via-slate-700 to-indigo-600 dark:from-white dark:via-slate-200 dark:to-indigo-400 bg-clip-text text-transparent font-black">
              MockAI
            </span>
          </div>

          <div className="flex items-center gap-3">
            <ThemeToggle />
            <button
              onClick={() => navigate("/auth")}
              className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100 hover:text-slate-900 shadow-sm transition-all cursor-pointer dark:border-slate-800 dark:bg-slate-950 dark:text-slate-300 dark:hover:bg-slate-900 dark:hover:text-white"
            >
              Sign In
            </button>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <main className="flex-1 flex flex-col justify-center py-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto w-full gap-16">
        <div className="text-center max-w-3xl mx-auto space-y-6">
          <div className="inline-flex items-center gap-1.5 rounded-full border border-indigo-500/30 bg-indigo-500/10 px-4 py-1.5 text-xs font-bold text-indigo-600 dark:text-indigo-300 shadow shadow-indigo-500/5 animate-pulse">
            <Sparkles className="h-3.5 w-3.5" />
            Next-Gen AI Interviewer
          </div>

          <h1 className="text-4xl sm:text-6xl font-extrabold tracking-tight text-slate-900 dark:text-white leading-tight">
            Master Your Next Interview with{" "}
            <span className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 bg-clip-text text-transparent">
              Generative AI
            </span>
          </h1>

          <p className="text-base sm:text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
            Practice realistic, role-specific text interviews. Receive instant scoring metrics, detailed feedback, target syllabus weak-spot analysis, and custom study plans generated by Gemini.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
            <button
              onClick={() => navigate("/auth")}
              className="group flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 px-6 py-3.5 text-sm font-bold text-white shadow-xl shadow-indigo-500/20 hover:opacity-95 active:scale-[0.98] transition-all cursor-pointer w-full sm:w-auto justify-center"
            >
              Get Started for Free
              <ArrowRight className="h-4.5 w-4.5 transition-transform group-hover:translate-x-0.5" />
            </button>
            <a
              href="#features"
              className="flex items-center justify-center gap-1 text-xs font-bold text-slate-600 hover:text-slate-900 dark:text-slate-400 dark:hover:text-slate-200 transition-colors border border-slate-200 bg-white/80 hover:bg-slate-100 dark:border-slate-800 rounded-xl px-6 py-3.5 dark:bg-slate-950/30 dark:hover:bg-slate-900/30 w-full sm:w-auto shadow-sm"
            >
              Learn More
            </a>
          </div>
        </div>

        {/* Feature Cards Grid */}
        <section id="features" className="space-y-8 pt-8">
          <div className="text-center space-y-2">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white">How MockAI Works</h2>
            <p className="text-xs text-slate-500 dark:text-slate-400">Advanced AI capabilities simulating professional evaluations</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {/* Card 1 */}
            <div className="rounded-2xl border border-slate-200 bg-white/80 p-6 space-y-4 shadow-sm hover:border-slate-300 transition-all flex flex-col justify-between dark:border-slate-900 dark:bg-slate-900/40 dark:hover:border-slate-800">
              <div className="space-y-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 shadow-sm">
                  <BrainCircuit className="h-5 w-5" />
                </div>
                <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Dynamic AI Generation</h3>
                <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed">
                  Questions are generated dynamically by Gemini based on your skills, target job role, difficulty level, and prior question context to prevent repetition.
                </p>
              </div>
            </div>

            {/* Card 2 */}
            <div className="rounded-2xl border border-slate-200 bg-white/80 p-6 space-y-4 shadow-sm hover:border-slate-300 transition-all flex flex-col justify-between dark:border-slate-900 dark:bg-slate-900/40 dark:hover:border-slate-800">
              <div className="space-y-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-purple-500/10 text-purple-600 dark:text-purple-400 shadow-sm">
                  <Award className="h-5 w-5" />
                </div>
                <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Real-Time Scoring</h3>
                <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed">
                  Each answer is analyzed for technical correctness, communication clarity, and question relevance, returning instant, constructive coaching feedback.
                </p>
              </div>
            </div>

            {/* Card 3 */}
            <div className="rounded-2xl border border-slate-200 bg-white/80 p-6 space-y-4 shadow-sm hover:border-slate-300 transition-all flex flex-col justify-between dark:border-slate-900 dark:bg-slate-900/40 dark:hover:border-slate-800">
              <div className="space-y-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-pink-500/10 text-pink-600 dark:text-pink-400 shadow-sm">
                  <BarChart3 className="h-5 w-5" />
                </div>
                <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Weak Area Tagging</h3>
                <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed">
                  Our system keeps track of topics where you scored lowest and maps them to specific syllabus domains requiring further practice.
                </p>
              </div>
            </div>

            {/* Card 4 */}
            <div className="rounded-2xl border border-slate-200 bg-white/80 p-6 space-y-4 shadow-sm hover:border-slate-300 transition-all flex flex-col justify-between dark:border-slate-900 dark:bg-slate-900/40 dark:hover:border-slate-800">
              <div className="space-y-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-green-500/10 text-green-600 dark:text-green-400 shadow-sm">
                  <ListChecks className="h-5 w-5" />
                </div>
                <h3 className="text-sm font-bold text-slate-800 dark:text-slate-200">Personalized Roadmaps</h3>
                <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed">
                  Get a personalized, step-by-step learning checklist after completing the interview to help you patch up knowledge gaps.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="w-full border-t border-slate-200 py-6 text-center text-[10px] text-slate-500 bg-white/50 dark:border-slate-900 dark:text-slate-500 dark:bg-slate-950/50 transition-colors">
        &copy; {new Date().getFullYear()} MockAI Interview Assistant. Built with React, FastAPI, MongoDB, and Google Gemini API.
      </footer>
    </div>
  );
};
export default Landing;
